import { jsPDF } from 'jspdf';
import { AgendaItem } from './types';

export function generateAgendaPDF(
    title: string,
    duration: number,
    items: AgendaItem[]
) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let y = margin;

    // Header
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text(title, margin, y);
    y += 10;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(`Duration: ${duration} min  |  ${items.length} sections`, margin, y);
    y += 4;

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.5);
    doc.line(margin, y, margin + contentWidth, y);
    y += 10;

    // Agenda items
    let runningTime = 0;
    items.forEach((item, index) => {
        // Check if we need a new page
        if (y > 260) {
            doc.addPage();
            y = margin;
        }

        // Time block
        const startMin = runningTime;
        const endMin = runningTime + item.duration;

        // Section number + time
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(120, 120, 120);
        doc.text(`${startMin} - ${endMin} min`, margin, y);

        // Section title
        doc.setFontSize(13);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(30, 30, 30);
        doc.text(`${index + 1}. ${item.title}`, margin, y + 6);

        // Duration badge
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(100, 100, 100);
        const durationText = `${item.duration} min`;
        const textWidth = doc.getTextWidth(durationText);
        doc.roundedRect(margin + contentWidth - textWidth - 10, y - 1, textWidth + 8, 8, 2, 2, 'S');
        doc.text(durationText, margin + contentWidth - textWidth - 6, y + 4.5);

        y += 10;

        // Notes
        if (item.notes) {
            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(80, 80, 80);
            const noteLines = doc.splitTextToSize(item.notes, contentWidth - 10);
            doc.text(noteLines, margin + 5, y);
            y += noteLines.length * 5;
        }

        y += 6;
        runningTime += item.duration;
    });

    // Footer
    y += 4;
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, margin + contentWidth, y);
    y += 8;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by SkipScore  |  ${new Date().toLocaleDateString()}`, margin, y);

    // Download
    const safeTitle = title.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '-').toLowerCase();
    doc.save(`agenda-${safeTitle}.pdf`);
}
