import { jsPDF } from 'jspdf';
import { AgendaItem } from './types';

function drawSkipScoreLogo(doc: jsPDF, x: number, y: number, size: number) {
    // Skip triangle (orange #F97316)
    doc.setFillColor(249, 115, 22);
    doc.triangle(
        x, y + size,             // bottom-left
        x, y,                    // top-left
        x + size * 0.67, y + size * 0.5,  // right-center
        'F'
    );

    // Score triangle (teal #0D9488)
    doc.setFillColor(13, 148, 136);
    doc.triangle(
        x + size * 0.83, y,              // top
        x + size * 1.42, y + size * 0.5, // right-center
        x + size * 0.83, y + size,       // bottom
        'F'
    );
}

export function generateAgendaPDF(
    title: string,
    duration: number,
    items: AgendaItem[]
) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let y = margin;

    // Header
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text(title, margin, y);
    y += 10;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(`Duration: ${duration} min  |  ${items.length} sections`, margin, y);
    y += 6;

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.5);
    doc.line(margin, y, margin + contentWidth, y);
    y += 12;

    // Agenda items
    let runningTime = 0;
    items.forEach((item, index) => {
        // Check if we need a new page (with enough room for section)
        if (y > 245) {
            doc.addPage();
            y = margin;
        }

        // Time block
        const startMin = runningTime;
        const endMin = runningTime + item.duration;

        // Section number + time
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(120, 120, 120);
        doc.text(`${startMin} - ${endMin} min`, margin, y);
        y += 7;

        // Section title
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(30, 30, 30);
        doc.text(`${index + 1}. ${item.title}`, margin, y);

        // Duration badge
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(100, 100, 100);
        const durationText = `${item.duration} min`;
        const textWidth = doc.getTextWidth(durationText);
        doc.roundedRect(margin + contentWidth - textWidth - 10, y - 5, textWidth + 8, 8, 2, 2, 'S');
        doc.text(durationText, margin + contentWidth - textWidth - 6, y);

        y += 4;

        // Notes
        if (item.notes) {
            y += 3;
            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(80, 80, 80);
            const noteLines = doc.splitTextToSize(item.notes, contentWidth - 10);
            doc.text(noteLines, margin + 5, y);
            y += noteLines.length * 5;
        }

        // Spacing between sections
        y += 12;
        runningTime += item.duration;
    });

    // Footer
    y += 6;

    // Check if footer needs a new page
    if (y > 265) {
        doc.addPage();
        y = margin;
    }

    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, margin + contentWidth, y);
    y += 10;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by SkipScore  |  ${new Date().toLocaleDateString()}`, margin, y);

    // SkipScore logo below the generated line
    y += 6;
    drawSkipScoreLogo(doc, margin, y, 8);

    // Download
    const safeTitle = title.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '-').toLowerCase();
    doc.save(`agenda-${safeTitle}.pdf`);
}
